export class Jugador {
    constructor(
    public idnumerocarnet: number,
    public idclub:         number,
    public fechainscr:     Date,
    public apellido:       string,
    public nombre:         string,
    public fecnac:         Date,
    public tipodoc:        string,
    public documento:      string,
    public pasaporte:      string,
    public nacionalidad:   string,
    public pase:           string,
    public sexo:           string,
    public domicilio:      string,
    public localidad:      string,
    public codigoPostal:   string,
    public provincia:      string,
    public telefono:       string,
    public otroTel:        string,
    public federacion:     string,
    public disciplina:     string,
    public actividad:      string,
    public marca:          string,
    public cluborigen:     string,
    public clubactual:     string,
    public licencia:       string,
    public clasificado:    string,
    public categoria:      string,
    public activado:       string,
    public foto:           Blob,
    public obraSocial:     string,
    public email:          string,
    public nroChequera:    string,
    public rama:           string,
    public nrotarjeta:     number,
    public nro:            number,
    public juega:          boolean,
    public ordenp:         number,
    public puesto:         number,
    public titular:        boolean,
    ){}
}
